version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      docker_compose_net:
        aliases:
          - backend
    ports:
      - 8080:80
    volumes:
      - backend_vol:/tmp

  db:
    image: mysql:8.0.27
    networks:
      docker_compose_net:
        aliases:
          - db
    environment:
      MYSQL_ROOT_PASSWORD: db-57xsl
      MYSQL_DATABASE: example
    volumes:
      - database:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      docker_compose_net:
        aliases:
          - frontend
    volumes:
      - frontend_vol:/code
    ports:
      - 3000:3000

networks:
  docker_compose_net:
    name: docker_compose_net

volumes:
  backend_vol:
  database:
  frontend_vol:
