version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - docker-compose-network

  db:
    image: mysql:8.0.27
    environment:
      - "MYSQL_ROOT_PASSWORD=db-57xsl"
      - "MYSQL_DATABASE=example"
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      docker-compose-network:
        aliases:
          - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - docker-compose-network


volumes:
  mysqldb:
  java-vol:

networks:
  docker-compose-network:
