name: Deploy With ArgoCD

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-argocd:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Deploy Application to Argo CD
        run: |
          sleep 30s
          cd /home/ubuntu/actions-runner/_work/final-project/final-project/infrastructure/argocd_manifest
          aws eks update-kubeconfig --region us-east-2 --name staging-ddriham
          kubectl apply -f react_app.yaml
          sleep 30s
          aws eks update-kubeconfig --region us-east-2 --name dev-ddriham
          kubectl apply -f react_app.yaml

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

    
