name: Deploy With ArgoCD

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-argocd:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Deploy Application to Argo CD
        run: |
          cd /home/ubuntu/actions-runner/_work/final-project/final-project/infrasturcture/argocd_manifest
          kubectl apply -f react_app.yaml

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    
