name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test application
        run: |
          docker-compose up --build -d
          sleep 10 # Adjust sleep time as needed
          curl localhost:3000 # Adjust port if needed
          docker-compose down

      - name: Login to Docker Hub with token
        if: success()
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }} 

      - name: Push backend Docker image
        if: success()
        run: |
          docker push ddriham/react-java0mysql-main-backend:latest
          docker push ddriham/react-java0mysql-main-backend:${GITHUB_RUN_NUMBER}

      - name: Push frontend Docker image
        if: success()
        run: |
          docker push ddriham/react-java0mysql-main-frontend:latest
          docker push ddriham/react-java0mysql-main-frontend:${GITHUB_RUN_NUMBER}
