name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build & Test
        run: |
          docker-compose up --build -d
          sleep 10 
          curl localhost:3000 
          docker-compose down

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push backend image
        run: |
          docker push ddriham/react-java0mysql-main-backend:latest
          docker push ddriham/react-java0mysql-main-backend:${GITHUB_RUN_NUMBER}

      - name: Push frontend image
        run: |
          docker push ddriham/react-java0mysql-main-frontend:latest
          docker push ddriham/react-java0mysql-main-frontend:${GITHUB_RUN_NUMBER}
