name: Deploy Infrastructure

on:
  workflow_run:
    workflows: ["CI"] 
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Initialize and Apply Terragrunt Configuration
        run: |
          cd /home/ubuntu/actions-runner/_work/final-project/final-project/infrastructure
          terragrunt run-all apply --terragrunt-non-interactive
          
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

