name: Deploy Infrastructure

on:
  workflow_run:
    workflows: ["CI"] 
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted] # Ensure this matches your self-hosted runner's labels
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Initialize and Apply Terragrunt Configuration
        run: |
          cd infrastructure
          terragrunt init
          terragrunt apply -auto-approve
        env:
          # Your environment variables, like cloud provider credentials
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

